#ifndef _NODE_MONITOR_H
#define _NODE_MONITOR_H
enum {
    B_NODE_MONITOR = '_NDM',
    B_STOP_WATCHING = 0x0001,
    B_WATCH_NAME = 0x0002,
    B_WATCH_STAT = 0x0004,
    B_WATCH_ATTR = 0x0008,
    B_WATCH_DIRECTORY = 0x0010,
    B_WATCH_ALL = 0x001f,
    B_WATCH_MOUNT = 0x0020,
    B_WATCH_INTERIM_UPDATE = 0x0040
};
enum {
    B_ENTRY_CREATED = 1,
    B_ENTRY_REMOVED = 2,
    B_ENTRY_MOVED = 3,
    B_STAT_CHANGED = 4,
    B_ATTR_CHANGED = 5,
    B_DEVICE_MOUNTED = 6,
    B_DEVICE_UNMOUNTED = 7
};
#endif
